### ISSUE TITLE
Various port setting values lost in UI

### ISSUE THREAD

**Issue by duncangreene** [google/testrun#1285]
**Describe the bug**
Various port setting values appear lost in UI after navigating away from Settings pane, as shown in below video. Namely the port selection and the 'ports mode'.

https://github.com/user-attachments/assets/3cf553b8-5be1-4bff-a9c7-98bb4ad83a37

**To Reproduce**
Follow steps in above video.

**Expected behavior**
Port settings/values maintained and 'ports mode' value does not appear empty.

**Environment (please provide the following information about your setup):**
 - Version 2.2

**Comment by duncangreene** [comment]
Just adding that changing Log Level or Monitoring values and then clicking "Save" causes the 'Two ports' text to disappear too.

**Comment by KrystsinaT** [comment]
The issue has been reported 416209905.

**Comment by KrystsinaT** [comment]
The issue has been resolved in 416209905 and will be released in version 2.2.2.

**Comment by duncangreene** [comment]
@KrystsinaT this UI issue is still present in 2.2.2. Please reopen.
